# Generated by Django 6.0.1 on 2026-02-04 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marque', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'published')], default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car/')),
                ('proprio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_proprio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
